import type { Metadata } from "next";
import { Work_Sans, Plus_Jakarta_Sans } from "next/font/google";
import StyledComponentsRegistry from "@/lib/registry";
import { ThemeProvider } from "@/theme/theme";
import GlobalStyle from "@/global/globalStyle";
import { ReduxProvider } from "@/lib/reduxProvider";

const workSans = Work_Sans({ subsets: ["latin"], variable: "--work-sans" });
const JakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"], variable: "--jakarta-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} ${JakartaSans.variable}`}>
        <StyledComponentsRegistry>
          <ReduxProvider>
            <ThemeProvider>
              <GlobalStyle />
              {children}
            </ThemeProvider>
          </ReduxProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
